Add solutions for 0 homework
voron434/itc-frontend pull request #1
Opened 2018-03-10 12:30 UTC by voron434

2018-03-10 16:46 UTC, mlshv commented
Имя репки и папок не по-православному
http://telegra.ph/Kak-sdavat-domashku-03-10

2018-03-10 18:14 UTC, voron434 commented
На тот момент еще небыло этого, но ок, принято

2018-03-12 07:28 UTC, mlshv requested changes
ты крутой

кость функциональная

2018-03-12 07:28 UTC, mlshv commented on homework0/index.js
> +const plus = (...args) => args.reduce(
ВОТ ЭТО РЕСПЕКТ

2018-03-12 07:28 UTC, mlshv commented on homework0/index.js
> +const plus = (...args) => args.reduce(
прям респектище

2018-03-12 07:28 UTC, mlshv commented on homework0/index.js
> +  if (result === undefined) {return def} else {return result}
можно просто `if (!result)`
но я бы написал `return result ? result : def`

2018-03-12 07:28 UTC, mlshv commented on homework0/index.js
> +      if (currentObject !== undefined) {
`if (currentObject)`

2018-03-12 15:18 UTC, voron434 commented
Я еще умнее придумал

2018-03-14 09:14 UTC, mlshv approved these changes
классно

2018-03-14 09:14 UTC, merged