Первая
voron434/itc-frontend pull request #2
Opened 2018-03-19 23:30 UTC by voron434

2018-03-19 23:33 UTC, voron434 commented
Там вроде только рефреша нет, но уже полтретьего и мне пора спать...

2018-03-22 07:34 UTC, mlshv requested changes

2018-03-22 07:34 UTC, mlshv commented on homework1/index.js
> +setTimeout( main, 10000 )
оно только один раз запустится

2018-03-22 13:31 UTC, voron434 commented on homework1/index.js
> +setTimeout( main, 10000 )
* Поправил с Timeout на Interval
* обрабатываю дефолтные значения реддита не через onerror, а ещё и сам дополнительно, чтоб в консоль не летело

2018-04-22 18:59 UTC, mlshv commented
кайф

2018-04-22 18:59 UTC, merged